font_family JetBrainsMono Nerd Font
font_size 13.0
font_style Regular
window_padding_width 6
include ./Gruvbox Dark.conf

disable_ligatures yes
enable_audio_bell no

shell_integration disabled

cursor_shape block
cursor_blink_interval 0

url_style curly

remember_window_size no
scollbar_handle_opacity 0
scollbar_track_opacity 0
scollbar_track_hover_opacity 0
cursor_trail 0
confirm_os_window_close 0

sync_to_monitor no
